import Head from "next/head";
import Image from "next/image";
import "bootstrap/dist/css/bootstrap.css";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div class="row">
          {[...Array(10)].map((_, i) => {
            return (
              <div class="col-3 mt-5">
                <div class="card" style={{ width: "18rem" }}>
                  {/* <img class="card-img-top" alt="Card image cap"></img> */}
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">
                      Some quick example text to build on the card title and
                      make up the bulk of the card's content.
                    </p>
                    <a href="#" class="btn btn-primary">
                      Go somewhere
                    </a>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}
